{
 "title": "Synthetics",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg by(instance) (probe_duration_seconds)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status Codes",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "probe_http_status_code", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "HTTP SSL",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "group by(target) (probe_http_ssl)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTPS Redirects",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "group by(target) (probe_http_redirects)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}