{
 "title": "PostgreSQL (swarmstack)",
 "description": "Dashboard works with postgres_exporter for prometheus\n\nhttps://github.com/swarmstack/postgresql-exporters",
 "tags": [ "postgresql" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "server",
    "label": "Server",
    "query": "query_result(pg_postmaster_start_time_seconds{server!=\"\"})"
   },
   { "name": "datname", "label": "Database", "query": "label_values(datname)" },
   {
    "name": "mode",
    "label": "Table Lock Type",
    "query": "label_values({mode=~\"accessexclusivelock|accesssharelock|exclusivelock|rowexclusivelock|rowsharelock|sharelock|sharerowexclusivelock|shareupdateexclusivelock\"}, mode)"
   },
   {
    "name": "device",
    "label": "Device",
    "query": "label_values(node_disk_reads_completed_total{instance=~\"$server_no_port\", device!~\"dm-.+\"}, device)"
   },
   {
    "name": "server_no_port",
    "label": "Device Host",
    "query": "query_result(label_replace(pg_postmaster_start_time_seconds{server!=\"\"}, \"server\", \"$1:9100\", \"server\", \"(.*):[0-9]+\"))"
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Top Changes (INSERT/UPDATE/DELETE)",
   "type": "timeseries",
   "description": "Number of rows inserted by queries in this database, Number of rows updated by queries in this database, Number of rows deleted by queries in this database",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(1, sum(increase(pg_stat_database_tup_inserted{server=~\"$server\", datname=~\"$datname\"}[$__interval])) by (server,datname))",
     "legendFormat": "{{server}} ({{datname}}) INSERT"
    },
    {
     "expr": "topk(1, sum(increase(pg_stat_database_tup_updated{server=~\"$server\", datname=~\"$datname\"}[$__interval])) by (server,datname))",
     "legendFormat": "{{server}} ({{datname}}) UPDATE"
    },
    {
     "expr": "topk(1, sum(increase(pg_stat_database_tup_deleted{server=~\"$server\", datname=~\"$datname\"}[$__interval])) by (server,datname))",
     "legendFormat": "{{server}} ({{datname}}) DELETE"
    }
   ]
  },
  {
   "title": "Last Transaction Replay",
   "type": "timeseries",
   "description": "Replication last transaction replay behind master in seconds",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(pg_replication_lag{server=~\"$server\"}) by (server)",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Top Transaction Commits",
   "type": "timeseries",
   "description": "Number of transactions in this database that have been committed",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(2, sum(increase(pg_stat_database_xact_commit{server=~\"$server\", datname=~\"$datname\"}[$__interval])) by (server,datname))",
     "legendFormat": "{{server}} ({{datname}})"
    }
   ]
  },
  {
   "title": "Replication Lag",
   "type": "timeseries",
   "description": "Replication lag behind master in bytes",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(pg_replication_replay_location_lag{server=~\"$server\"}) by (server,application_name)",
     "legendFormat": "{{server}} to {{application_name}}"
    }
   ]
  },
  {
   "title": "Top Transaction Rollbacks",
   "type": "timeseries",
   "description": "Number of transactions in this database that have been rolled back",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(2, sum(increase(pg_stat_database_xact_rollback{server=~\"$server\", datname=~\"$datname\"}[$__interval])) by (server,datname))",
     "legendFormat": "{{server}} ({{datname}})"
    }
   ]
  },
  {
   "title": "Longest Transaction",
   "type": "timeseries",
   "description": "Max duration in seconds any active transaction has been running",
   "gridPos": { "h": 5, "w": 15, "x": 9, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(pg_stat_activity_max_tx_duration{server=~\"$server\", datname=~\"$datname\", state!~\"idle.*\"}) by (server,datname)",
     "legendFormat": "{{server}} ({{datname}})"
    }
   ]
  },
  {
   "title": "Top Filesystem Fill",
   "type": "timeseries",
   "description": "Top filesystems filled, in percent across selected Device Host(s)",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "topk(4, 1 - node_filesystem_free_bytes{instance=~\"$server_no_port\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\", mountpoint!=\"/boot\"} / node_filesystem_size_bytes{instance=~\"$server_no_port\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\", mountpoint!=\"/boot\"})",
     "legendFormat": "{{instance}} ({{mountpoint}})"
    }
   ]
  },
  {
   "title": "% to XID Wraparound",
   "type": "timeseries",
   "description": "Percentage towards transaction ID wraparound, fatal to database if exhausted",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ccp_transaction_wraparound_percent_towards_wraparound{server=~\"$server\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Conflicts/Deadlocks",
   "type": "timeseries",
   "description": "Number of queries canceled due to conflicts with recovery in this database. (Conflicts occur only on standby servers). Number of deadlocks detected in this database.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(pg_stat_database_conflicts{server=~\"$server\", datname=~\"$datname\"}[30m]) > 0) by (server,datname)",
     "legendFormat": "Conflicts: {{server}} - {{datname}}"
    },
    {
     "expr": "sum(increase(pg_stat_database_deadlocks{server=~\"$server\", datname=~\"$datname\"}[30m]) > 0) by (server,datname)",
     "legendFormat": "Deadlocks: {{server}} {{datname}}"
    }
   ]
  },
  {
   "title": "Conflicts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Due to Dropped Tables",
     "type": "graph",
     "description": "Number of queries in this database that have been canceled due to dropped tablespaces",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(pg_stat_database_conflicts_confl_tablespace{server=~\"$server\",datname=~\"$datname\"}[30m]) > 0",
       "legendFormat": "{{server}} - {{datname}}"
      }
     ]
    },
    {
     "title": "Due to Lock Timeouts",
     "type": "graph",
     "description": "Number of queries in this database that have been canceled due to lock timeouts",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(pg_stat_database_conflicts_confl_lock{server=~\"$server\",datname=~\"$datname\"}[30m]) > 0",
       "legendFormat": "{{server}} - {{datname}}"
      }
     ]
    },
    {
     "title": "Due to Old Snapshots",
     "type": "graph",
     "description": "Number of queries in this database that have been canceled due to old snapshots",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(pg_stat_database_conflicts_confl_snapshot{server=~\"$server\",datname=~\"$datname\"}[30m])",
       "legendFormat": "{{server}} - {{datname}}"
      }
     ]
    },
    {
     "title": "Due to Pinned Buffers",
     "type": "graph",
     "description": "Number of queries in this database that have been canceled due to pinned buffers",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(pg_stat_database_conflicts_confl_bufferpin{server=~\"$server\",datname=~\"$datname\"}[30m])",
       "legendFormat": "{{server}} - {{datname}}"
      }
     ]
    },
    {
     "title": "Due to Deadlocks",
     "type": "graph",
     "description": "Number of queries in this database that have been canceled due to deadlocks",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(pg_stat_database_conflicts_confl_deadlock{server=~\"$server\",datname=~\"$datname\"}[30m])",
       "legendFormat": "{{server}} - {{datname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Background Writer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Top BGWriter Checkpoint Write Time",
     "type": "graph",
     "description": "Total amount of time that has been spent in the portion of checkpoint processing where files are written to disk",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "topk(1, increase(pg_stat_bgwriter_checkpoint_write_time{server=~\"$server\"}[$__interval]))",
       "legendFormat": "{{server}}"
      }
     ]
    },
    {
     "title": "Top BGWriter Checkpoint Sync Time",
     "type": "graph",
     "description": "Total amount of time that has been spent in the portion of checkpoint processing where files are synchronized to disk",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "topk(1, increase(pg_stat_bgwriter_checkpoint_sync_time{server=~\"$server\"}[$__interval]))",
       "legendFormat": "{{server}}"
      }
     ]
    },
    {
     "title": "Top BGWriter Buffers Checkpoint",
     "type": "graph",
     "description": "Number of buffers written during checkpoints",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(1, increase(pg_stat_bgwriter_buffers_checkpoint{server=~\"$server\"}[$__interval]))",
       "legendFormat": "{{server}}"
      }
     ]
    },
    {
     "title": "Top BGWriter Buffers Clean",
     "type": "graph",
     "description": "Number of buffers written by the background writer",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(1, increase(pg_stat_bgwriter_buffers_clean{server=~\"$server\"}[$__interval]))",
       "legendFormat": "{{server}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Insert / Update / Delete",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Top Tuples Inserted",
     "type": "graph",
     "description": "Number of rows inserted by queries in this database",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(2, sum(increase(pg_stat_database_tup_inserted{datname=~\"$datname\", server=~\"$server\"}[$__interval])) by (server,datname))",
       "legendFormat": "{{server}} {{datname}}"
      }
     ]
    },
    {
     "title": "Top Tuples Updated",
     "type": "graph",
     "description": "Number of rows updated by queries in this database",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(2, sum(increase(pg_stat_database_tup_updated{datname=~\"$datname\", server=~\"$server\"}[$__interval])) by (server,datname))",
       "legendFormat": "{{server}} {{datname}}"
      }
     ]
    },
    {
     "title": "Top Tuples Deleted",
     "type": "graph",
     "description": "Number of rows deleted by queries in this database",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(2, sum(increase(pg_stat_database_tup_deleted{datname=~\"$datname\", server=~\"$server\"}[$__interval])) by (server,datname))",
       "legendFormat": "{{server}} {{datname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Reads and Writes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Top Tuples Read (table scan)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(1, sum(increase(pg_stat_database_tup_returned{datname=~\"$datname\", server=~\"$server\"}[$__interval])) by (server,datname))",
       "legendFormat": "{{server}} ({{datname}})"
      }
     ]
    },
    {
     "title": "Top Tuples Read (index scan)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(1, sum(increase(pg_stat_database_tup_fetched{datname=~\"$datname\", server=~\"$server\"}[$__interval])) by (server,datname))",
       "legendFormat": "{{server}} ({{datname}})"
      }
     ]
    },
    {
     "title": "Top Read Disk Latency",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "topk(1, (increase(node_disk_read_time_seconds_total{device=~\"$device\", instance=~\"$server_no_port\"}[$__interval]) / increase(node_disk_reads_completed_total{device=~\"$device\", instance=~\"$server_no_port\"}[$__interval])))",
       "legendFormat": "{{instance}} ({{device}})"
      }
     ]
    },
    {
     "title": "Top Write Disk Latency",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "topk(1, (increase(node_disk_write_time_seconds_total{device=~\"$device\", instance=~\"$server_no_port\"}[$__interval]) / increase(node_disk_writes_completed_total{device=~\"$device\", instance=~\"$server_no_port\"}[$__interval])))",
       "legendFormat": "{{instance}} ({{device}})"
      }
     ]
    },
    {
     "title": "Top Temp Files",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "decbytes", "label": "Rows" }
     ],
     "targets": [
      {
       "expr": "topk(1, sum(increase(pg_stat_database_temp_bytes{server=~\"$server\", datname=~\"$datname\"}[$__interval])) by (server,datname))",
       "legendFormat": "{{server}} ({{datname}}) index scans"
      }
     ]
    }
   ]
  },
  {
   "title": "Sizes and Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Top Database Sizes",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "topk(1, pg_database_size{server=~\"$server\"} > 10000000) by (datname)",
       "legendFormat": "{{server}} ({{datname}})"
      }
     ]
    },
    {
     "title": "Top Disk Used",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "topk(4, node_filesystem_size_bytes{instance=~\"$server_no_port\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\", mountpoint!=\"/boot\"} - node_filesystem_free_bytes{instance=~\"$server_no_port\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\", mountpoint!=\"/boot\"})",
       "legendFormat": "{{instance}} ({{mountpoint}})"
      }
     ]
    },
    {
     "title": "Top Table Size",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "topk(1, pg_table_total_bytes{server=~\"$server\"}) by (server)",
       "legendFormat": "{{server}} ({{table_name}})"
      }
     ]
    },
    {
     "title": "Top Table Index",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "topk(1,pg_table_index_bytes{server=~\"$server\"}) by (server)",
       "legendFormat": "{{server}} ({{table_name}})"
      }
     ]
    },
    {
     "title": "Top Table Rows",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(1,pg_table_row_estimate{server=~\"$server\"}) by (server)",
       "legendFormat": "{{server}} ({{table_name}})"
      }
     ]
    },
    {
     "title": "Top Table Toast",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "topk(1,pg_table_toast_bytes{server=~\"$server\"}) by (server)",
       "legendFormat": "{{server}} ({{table_name}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Table IO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Top Disk Blocks Read",
     "type": "graph",
     "description": "Number of disk blocks read from this table",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(2, increase(pg_statio_user_tables_heap_blks_read{server=~\"$server\"}[$__interval]))",
       "legendFormat": "{{server}} - {{schemaname}}.{{relname}}"
      }
     ]
    },
    {
     "title": "Top Buffer Hits",
     "type": "graph",
     "description": "Number of buffer hits in this table",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(2, increase(pg_statio_user_tables_heap_blks_hit{server=~\"$server\"}[$__interval]))",
       "legendFormat": "{{server}} - {{schemaname}}.{{relname}}"
      }
     ]
    },
    {
     "title": "Top Disk Blocks Read from Indexes",
     "type": "graph",
     "description": "Number of disk blocks read from all indexes on this table",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(2, increase(pg_statio_user_tables_idx_blks_read{server=~\"$server\"}[$__interval]))",
       "legendFormat": "{{server}} - {{schemaname}}.{{relname}}"
      }
     ]
    },
    {
     "title": "Top Buffer Hits from Indexes",
     "type": "graph",
     "description": "Number of buffer hits in all indexes on this table",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(2, increase(pg_statio_user_tables_idx_blks_hit{server=~\"$server\"}[$__interval]))",
       "legendFormat": "{{server}} - {{schemaname}}.{{relname}}"
      }
     ]
    },
    {
     "title": "Top Disk Blocks Read from TOAST Table",
     "type": "graph",
     "description": "Number of disk blocks read from this table's TOAST table (if any)",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(2, increase(pg_statio_user_tables_toast_blks_read{server=~\"$server\"}[$__interval]))",
       "legendFormat": "{{server}} - {{schemaname}}.{{relname}}"
      }
     ]
    },
    {
     "title": "Top Buffer Hits from TOAST Table",
     "type": "graph",
     "description": "Number of buffer hits in this table's TOAST table (if any)",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(2, increase(pg_statio_user_tables_toast_blks_hit{server=~\"$server\"}[$__interval]))",
       "legendFormat": "{{server}} - {{schemaname}}.{{relname}}"
      }
     ]
    },
    {
     "title": "Top Disk Blocks Read from TOAST Indexes",
     "type": "graph",
     "description": "Number of disk blocks read from this table's TOAST table indexes (if any)",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(2, increase(pg_statio_user_tables_tidx_blks_read{server=~\"$server\"}[$__interval]))",
       "legendFormat": "{{server}} - {{schemaname}}.{{relname}}"
      }
     ]
    },
    {
     "title": "Top Buffer Hits from TOAST Indexes",
     "type": "graph",
     "description": "Number of buffer hits in this table's TOAST table indexes (if any)",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(2, increase(pg_statio_user_tables_tidx_blks_hit{server=~\"$server\"}[$__interval]))",
       "legendFormat": "{{server}} - {{schemaname}}.{{relname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Table Locks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Top Table Locks",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(1, sum(pg_locks_count{datname=~\"$datname\", server=~\"$server\", mode=~\"$mode\"}) by (server, datname, mode))",
       "legendFormat": "{{server}} ({{datname}}) {{mode}}"
      }
     ]
    },
    {
     "title": "Access Exclusive",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(pg_locks_count{datname=~\"$datname\", server=~\"$server\", mode=~\"accessexclusivelock\"}) by (server, datname)",
       "legendFormat": "{{server}} ({{datname}})"
      }
     ]
    },
    {
     "title": "Exclusive",
     "type": "graph",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(pg_locks_count{datname=~\"$datname\", server=~\"$server\", mode=~\"exclusivelock\"}) by (server, datname)",
       "legendFormat": "{{server}} ({{datname}})"
      }
     ]
    },
    {
     "title": "Row Exclusive",
     "type": "graph",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(pg_locks_count{datname=~\"$datname\", server=~\"$server\", mode=~\"rowexclusivelock\"}) by (server, datname)",
       "legendFormat": "{{server}} ({{datname}})"
      }
     ]
    },
    {
     "title": "Share Update Exclusive",
     "type": "graph",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(pg_locks_count{datname=~\"$datname\", server=~\"$server\", mode=~\"shareupdateexclusivelock\"}) by (server, datname)",
       "legendFormat": "{{server}} ({{datname}})"
      }
     ]
    },
    {
     "title": "Share",
     "type": "graph",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(pg_locks_count{datname=~\"$datname\", server=~\"$server\", mode=~\"sharelock\"}) by (server, datname)",
       "legendFormat": "{{server}} ({{datname}})"
      }
     ]
    },
    {
     "title": "Row Share",
     "type": "graph",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(pg_locks_count{datname=~\"$datname\", server=~\"$server\", mode=~\"rowsharelock\"}) by (server, datname)",
       "legendFormat": "{{server}} ({{datname}})"
      }
     ]
    },
    {
     "title": "Share Row Exclusive",
     "type": "graph",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(pg_locks_count{datname=~\"$datname\", server=~\"$server\", mode=~\"sharerowexclusivelock\"}) by (server, datname)",
       "legendFormat": "{{server}} ({{datname}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Tables Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Top Sequential Scans",
     "type": "graph",
     "description": "Number of sequential scans initiated on this table",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(2, increase(pg_stat_user_tables_seq_scan{server=~\"$server\"}[$__interval]))",
       "legendFormat": "{{server}} - {{schemaname}}.{{relname}}"
      }
     ]
    },
    {
     "title": "Top Dead Tuples",
     "type": "graph",
     "description": "Estimated number of dead rows",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(2, pg_stat_user_tables_n_dead_tup{server=~\"$server\"})",
       "legendFormat": "{{server}} - {{schemaname}}.{{relname}}"
      }
     ]
    },
    {
     "title": "Top Rows Read by Sequential Scans",
     "type": "graph",
     "description": "Number of live rows fetched by sequential scans",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(2, increase(pg_stat_user_tables_seq_tup_read{server=~\"$server\"}[$__interval]))",
       "legendFormat": "{{server}} - {{schemaname}}.{{relname}}"
      }
     ]
    },
    {
     "title": "Top Rows Inserted",
     "type": "graph",
     "description": "Number of rows inserted",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(2, increase(pg_stat_user_tables_n_tup_ins{server=~\"$server\"}[$__interval]))",
       "legendFormat": "{{server}} - {{schemaname}}.{{relname}}"
      }
     ]
    },
    {
     "title": "Top Index Scans",
     "type": "graph",
     "description": "Number of index scans initiated on this table",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(2, increase(pg_stat_user_tables_idx_scan{server=~\"$server\"}[$__interval]))",
       "legendFormat": "{{server}} - {{schemaname}}.{{relname}}"
      }
     ]
    },
    {
     "title": "Top Rows Updated",
     "type": "graph",
     "description": "Number of rows updated",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(2, increase(pg_stat_user_tables_n_tup_upd{server=~\"$server\"}[$__interval]))",
       "legendFormat": "{{server}} - {{schemaname}}.{{relname}}"
      }
     ]
    },
    {
     "title": "Top Rows Read by Index Scans",
     "type": "graph",
     "description": "Number of live rows fetched by index scans",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(2, increase(pg_stat_user_tables_idx_tup_fetch{server=~\"$server\"}[$__interval]))",
       "legendFormat": "{{server}} - {{schemaname}}.{{relname}}"
      }
     ]
    },
    {
     "title": "Top Rows Deleted",
     "type": "graph",
     "description": "Number of rows deleted",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(2, increase(pg_stat_user_tables_n_tup_del{server=~\"$server\"}[$__interval]))",
       "legendFormat": "{{server}} - {{schemaname}}.{{relname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Top Transaction Commits",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(2, sum(increase(pg_stat_database_xact_commit{server=~\"$server\", datname=~\"$datname\"}[10m])) by (server,datname))",
       "legendFormat": "{{server}} ({{datname}})"
      }
     ]
    },
    {
     "title": "Top Transaction Rollbacks",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(2, sum(increase(pg_stat_database_xact_rollback{server=~\"$server\", datname=~\"$datname\"}[10m])) by (server,datname))",
       "legendFormat": "{{server}} ({{datname}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Vacuum / Analyze",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Oldest Auto Analyze",
     "type": "table-old",
     "description": "Last time at which this table was analyzed by the autovacuum daemon",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 32 },
     "targets": [
      {
       "expr": "bottomk(2, pg_stat_user_tables_last_autoanalyze{server=~\"$server\"} * 1000)",
       "legendFormat": "{{server}} - {{schemaname}}.{{relname}}"
      }
     ]
    },
    {
     "title": "Top Auto Vacuum Count",
     "type": "table-old",
     "description": "Number of times this table has been vacuumed by the autovacuum daemon",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 32 },
     "targets": [
      {
       "expr": "topk(2, pg_stat_user_tables_autovacuum_count{server=~\"$server\"})",
       "legendFormat": "{{server}} - {{schemaname}}.{{relname}}"
      }
     ]
    },
    {
     "title": "Lowest Non-Zero Auto Analyze Count",
     "type": "table-old",
     "description": "Number of times this table has been analyzed by the autovacuum daemon",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 32 },
     "targets": [
      {
       "expr": "bottomk(2, pg_stat_user_tables_autoanalyze_count{server=~\"$server\"} > 0)",
       "legendFormat": "{{server}} - {{schemaname}}.{{relname}}"
      }
     ]
    },
    {
     "title": "Oldest Auto Vacuum",
     "type": "table-old",
     "description": "Last time at which this table was vacuumed by the autovacuum daemon",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 37 },
     "targets": [
      {
       "expr": "bottomk(2, pg_stat_user_tables_last_autovacuum{server=~\"$server\"} * 1000)",
       "legendFormat": "{{server}} - {{schemaname}}.{{relname}}"
      }
     ]
    },
    {
     "title": "Top Auto Analyze Count",
     "type": "table-old",
     "description": "Number of times this table has been analyzed by the autovacuum daemon",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 37 },
     "targets": [
      {
       "expr": "topk(2, pg_stat_user_tables_autoanalyze_count{server=~\"$server\"})",
       "legendFormat": "{{server}} - {{schemaname}}.{{relname}}"
      }
     ]
    },
    {
     "title": "Lowest Non-Zero Auto Vacuum Count",
     "type": "table-old",
     "description": "Number of times this table has been vacuumed by the autovacuum daemon",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 37 },
     "targets": [
      {
       "expr": "bottomk(2, pg_stat_user_tables_autovacuum_count{server=~\"$server\"} > 0)",
       "legendFormat": "{{server}} - {{schemaname}}.{{relname}}"
      }
     ]
    },
    {
     "title": "Oldest Manual Analyze",
     "type": "table-old",
     "description": "Last time at which this table was manually analyzed",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 42 },
     "targets": [
      {
       "expr": "bottomk(2, pg_stat_user_tables_last_analyze{server=~\"$server\"} * 1000 > 0)",
       "legendFormat": "{{server}} - {{schemaname}}.{{relname}}"
      }
     ]
    },
    {
     "title": "Top Manual Analyze Count",
     "type": "table-old",
     "description": "Number of times this table has been manually analyzed",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 42 },
     "targets": [
      {
       "expr": "topk(2, pg_stat_user_tables_analyze_count{server=~\"$server\"})",
       "legendFormat": "{{server}} - {{schemaname}}.{{relname}}"
      }
     ]
    },
    {
     "title": "Lowest Non-Zero Manual Analyze Count",
     "type": "table-old",
     "description": "Number of times this table has been manually analyzed",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 42 },
     "targets": [
      {
       "expr": "bottomk(2, pg_stat_user_tables_analyze_count{server=~\"$server\"} > 0)",
       "legendFormat": "{{server}} - {{schemaname}}.{{relname}}"
      }
     ]
    },
    {
     "title": "Oldest Manual Vacuum",
     "type": "table-old",
     "description": "Last time at which this table was manually vacuumed (not counting VACUUM FULL)",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 47 },
     "targets": [
      {
       "expr": "bottomk(2, pg_stat_user_tables_last_vacuum{server=~\"$server\"} * 1000 > 0)",
       "legendFormat": "{{server}} - {{schemaname}}.{{relname}}"
      }
     ]
    },
    {
     "title": "Top Manual Vacuum Count",
     "type": "table-old",
     "description": "Number of times this table has been manually vacuumed (not counting VACUUM FULL)",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 47 },
     "targets": [
      {
       "expr": "topk(2, pg_stat_user_tables_vacuum_count{server=~\"$server\"})",
       "legendFormat": "{{server}} - {{schemaname}}.{{relname}}"
      }
     ]
    },
    {
     "title": "Lowest Non-Zero Manual Vacuum Count",
     "type": "table-old",
     "description": "Number of times this table has been manually vacuumed (not counting VACUUM FULL)",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 47 },
     "targets": [
      {
       "expr": "bottomk(2, pg_stat_user_tables_vacuum_count{server=~\"$server\"} > 0)",
       "legendFormat": "{{server}} - {{schemaname}}.{{relname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "PG Internals",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Postmaster Start Time",
     "type": "table-old",
     "gridPos": { "h": 16, "w": 8, "x": 0, "y": 32 },
     "targets": [
      {
       "expr": "pg_postmaster_start_time_seconds{server=~\"$server\"} * 1000",
       "legendFormat": "{{server}}"
      }
     ]
    },
    {
     "title": "% to Emergency Vacuum",
     "type": "graph",
     "description": "Percentage towards emergency autovacuum process starting",
     "gridPos": { "h": 5, "w": 16, "x": 8, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ccp_transaction_wraparound_percent_towards_emergency_autovac{server=~\"$server\"}",
       "legendFormat": "{{server}}"
      }
     ]
    },
    {
     "title": "Top Idle Sessions",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(2, sum(pg_stat_activity_count{datname=~\"$datname\", server=~\"$server\", state=~\"idle.*\"}) by (server,datname,state))",
       "legendFormat": "{{server}} ({{datname}}) {{state}}"
      }
     ]
    },
    {
     "title": "Top Active sessions",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 37 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "topk(2, sum(pg_stat_activity_count{datname=~\"$datname\", server=~\"$server\", state=\"active\"}) by (server,datname))",
       "legendFormat": "{{server}} ({{datname}})"
      }
     ]
    },
    {
     "title": "Lowest Cache Hit Rate",
     "type": "graph",
     "gridPos": { "h": 5, "w": 16, "x": 8, "y": 43 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "bottomk(2, sum(pg_stat_database_blks_hit{server=~\"$server\", datname=~\"$datname\"}) by (server,datname) / (sum(pg_stat_database_blks_read{server=~\"$server\", datname=~\"$datname\"}) by (server,datname) + sum(pg_stat_database_blks_hit{server=~\"$server\", datname=~\"$datname\"}) by (server,datname))) < 99",
       "legendFormat": "{{server}} ({{datname}})"
      }
     ]
    }
   ]
  }
 ]
}