apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: automate-onepassword
  namespace: automate
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: automate-onepassword
    creationPolicy: Owner
  data:
    - secretKey: DROPBOX_CLIENT_ID
      remoteRef:
        key: Dropbox App - Automatox
        property: username
    - secretKey: DROPBOX_CLIENT_SECRET
      remoteRef:
        key: Dropbox App - Automatox
        property: credential
    - secretKey: TODOIST_CLIENT_ID
      remoteRef:
        key: Todoist App - AutoMate
        property: username
    - secretKey: TODOIST_CLIENT_SECRET
      remoteRef:
        key: Todoist App - AutoMate
        property: credential
    - secretKey: TODOIST_VERIFICATION_TOKEN
      remoteRef:
        key: Todoist App - AutoMate
        property: verification token
