{
 "title": "Miniflux",
 "time": { "from": "2025-04-06T22:26:08.386Z", "to": "2025-04-07T01:32:44.862Z" },
 "panels": [
  {
   "title": "Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "miniflux_users", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Feeds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "miniflux_feeds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Entries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "miniflux_entries", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Broken Feeds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "miniflux_broken_feeds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Database Open Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "miniflux_db_open_connections", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Database Connections Wait Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "miniflux_db_connections_wait_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database Connections Max Lifetime Closed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "miniflux_db_connections_max_lifetime_closed",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database Connections Max Idle Time Closed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "miniflux_db_connections_max_idle_time_closed",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database Connections Max Idle Closed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "miniflux_db_connections_max_idle_closed",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database Connections in Use",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    { "expr": "miniflux_db_connections_in_use", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Database Connections Idle",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    { "expr": "miniflux_db_connections_idle", "legendFormat": "__auto" }
   ]
  }
 ]
}