name: Lint

on:
  workflow_call:
    inputs:
      app_version:
        default: latest-lint
        required: false
        type: string
      registry:
        default: sjc.vultrcr.com/frankistry
        required: false
        type: string

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    env:
      APP_VERSION: ${{ inputs.app_version }}
      REGISTRY: ${{ inputs.registry }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
      - uses: opentofu/setup-opentofu@v1
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - uses: pre-commit/action@v3.0.1
