name: Lint

on:
  workflow_call:
    inputs:
      app_version:
        default: latest-lint
        required: false
        type: string
      registry:
        default: sjc.vultrcr.com/frankistry
        required: false
        type: string

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-dotnet@v5
      - name: Setup Fantomas
        run: dotnet tool restore
      - uses: opentofu/setup-opentofu@v2
      - uses: actions/setup-python@v6
        with:
          python-version: 3.12
      - name: Run pre-commit
        run: |
          pip install pre-commit==4.6
          pre-commit run --all-files --show-diff-on-failure
